#' Calculate threshold for theoretical False Discovery Rate (tFDR)
#'
#' Determine the posterior probability threshold at which to control the
#' false discovery rate (FDR) by estimating the theoretical FDR given the observed
#' posterior probabilities.
#'
#' @param post_prob vector of estimated posterior probabilities
#' @param fdr numerical value; the desired false discovery rate (FDR)
#'
#' @return Posterior probability threshold (numeric) to use in controlling the FDR.
#'
#' @details The function calculates the theoretical FDR at each observed posterior probability
#' by averaging \code{(1-post_prob)} over observations at least as large as that probability.
#' It returns the value of the first observation in \code{post_prob} for which the cumulative
#' average is greater than \code{fdr}.
#'
#' @export
#'
tfdr_thresh <- function(post_prob,fdr){
  post_prob <- sort(post_prob,decreasing=T)
  cumsum_1pp <- cumsum(1-post_prob)
  ## calculate tfdr at each post. prob.
  tfdr <- cumsum_1pp/(1:length(post_prob))
  ## indices of pp having tfdr larger than desired threshold
  tfdr_above_thresh <- which(tfdr>fdr)
  ## return posterior probability threshold that controls FDR
  return(post_prob[tfdr_above_thresh[1]])
}

#' Calculate theoretical False Discovery Rate (tFDR)
#'
#' Calculate the theoretical false discovery rate (tFDR) at a specified
#' posterior probability threshold.
#'
#' @param post_prob vector of estimated posterior probabilities
#' @param pp_thresh numerical value; the posterior probability threshold at which
#' to calculate the tFDR
#'
#' @return Theoretical FDR (numeric) at specified posterior probability threshold.
#'
#' @details The function estimates the theoretical FDR at the specified posterior probability
#' threshold by using the mean of \code{(1-post_prob)} for probabilities exceeding that threshold.
#'
#' @export
#'
tfdr <- function(post_prob,pp_thresh){
  post_prob <- post_prob[which(post_prob >= pp_thresh)]
  ## return tfdr
  return(mean(post_prob))
}


#' Calculate empirical False Discovery Rate (eFDR)
#'
#' Calculate the empirical False Discovery Rate (eFDR) given
#' observed results and results from permuted datasets. Takes
#' a vector of potential posterior probability thresholds and
#' calculates the eFDR for each threshold.
#'
#' @param true_res a list; results returned by \code{\link{estimate_config}} run
#' with real data
#' @param perm_res a list of lists; results returned by \code{\link{estimate_config}} run
#' with permuted datasets
#' @param thresholds vector of posterior probability thresholds for which to calculate eFDR
#' @param config numerical value; the column number of the configuration for which to
#' estimate eFDR values
#' @param multi_perm logical; denotes whether \code{perm_res} was generated by \code{permute_multi}
#'
#' @return vector of the eFDR for each posterior probability threshold tested.
#'
#' @export
#'
efdr <- function(true_res,perm_res,thresholds=seq(0.9999,0.9000,-.0005),config=NULL,multi_perm=F){
  # last configuration (alternative for all data sources/types) is default for posterior prob. eFDR
  if (is.null(config)) config <- ncol(true_res$post_prob)

  ## if multiple configurations, sum posteriors (allows for "at least" calculations and collapsing categories)
  if(length(config)> 1){
    pp <- rowSums(true_res$post_prob[,config])
    if(multi_perm){
      pp0 <- sapply(unlist(perm_res,recursive = F), function(x) rowSums(x[,config]))
    } else pp0 <- sapply(perm_res,function(x) rowSums(x$post_prob[,config]))
  } else{
    pp <- true_res$post_prob[,config]
    if(multi_perm){
      pp0 <- sapply(unlist(perm_res,recursive = F), function(x) x[,config])
    } else pp0 <- sapply(perm_res,function(x) x$post_prob[,config])
  }

  # calculate eFDR at each threshold
  efdr <- sapply(thresholds, function(x) mean(pp0>=x)/mean(pp>=x))
}


#' Posterior Probability threshold to control FDR
#'
#' Determine posterior probability threshold to use for controlling false discovery rate (FDR).
#' The function a vector of empirical FDR calculated for candidate posterior thresholds.
#' and returns a posterior probability threshold expected to control FDR at specified rate.
#'
#' @param efdr_res vector of eFDR values by potential posterior probability thresholds
#' @param fdr numerical value; desired/specified false discovery rate
#' @param tol the tolerance level for FDR control (i.e. half of the convergence window)
#' @param descending logical; denotes whether posterior probability thresholds are in
#' descending order
#' @param max_pp logical; denotes whether to return the maximum or minimum posterior probability
#' threshold which meets the FDR criteria
#'
#'
#' @return numerical value; posterior probability threshold if selected efdr was named
#' after probability value.
#' Otherwise, returns the index of the matching eFDR (with warning message).
#'
#' @export
#'
select_ppthresh <- function(efdr_res,fdr=0.05,tol=1e-3,descending=T,max_pp=T){
  all_matches <- which(efdr_res > (fdr-tol) & efdr_res < (fdr+tol))

  if (is.null(all_matches)) stop("No eFDR fuzzy-matched the specified FDR.\n
                             Expand posterior probability grid or relax tolerance threshold.")

  # if descending and max, or ascending and min, select maximum index
  if (descending==max_pp) select.idx <- max(all_matches)
  # otherwise, select minimum index
  else select.idx <- min(all_matches)

  # return index of matching threshold to control eFDR unless efdr_res named by threshold
  if (is.null(names(efdr_res)) | is.na(as.numeric(names(efdr_res)[select.idx]))){
    cat("Returning index of matching eFDR.")
    return(select.idx)
  } else return(as.numeric(names(efdr_res)[select.idx]))
}
