# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Density matrix calculation
#'
#' Calculate conditional joint densities for each configuration, given marginal
#' null and alternative densities, under the assumption of independence.
#'
#' @param Q matrix of configurations
#' @param D0 estimate for the null density function
#' @param D1 estimate for the alternative density function
#'
#' @return Returns a matrix estimating the conditional joint densities
#' under each configuration
#' (i.e. estimated probability of each configuration for each SNP).
#'
#' @export
#'
calc_Dmatrix <- function(Q, D0, D1) {
    .Call(`_Primo_calc_Dmatrix`, Q, D0, D1)
}

#' E Step
#'
#' Calculate posterior expectations given maximized estimate for \eqn{\pi} (the
#' proportion of SNPs coming from each configuration).
#'
#' @param old_pi vector of configuration proportions, fit through maximization
#' (usualy 2^J for J data types)
#' @param Dmat matrix of conditional joint densities under each configuration
#'
#' @return Returns a matrix estimating the posterior expectations
#' (i.e. estimated probability of each configuration for each SNP).
#'
#' @export
#'
e_step <- function(old_pi, Dmat) {
    .Call(`_Primo_e_step`, old_pi, Dmat)
}

#' E Step, using precalculated joint densities
#'
#' Calculate posterior expectations given maximized estimate for \eqn{\pi} (the
#' proportion of SNPs coming from each configuration).
#'
#' @param old_pi vector of configuration proportions, fit through maximization
#' (usualy 2^J for J data types)
#' @param Dmat matrix of conditional joint densities under each configuration
#'
#' @return Returns a matrix of column sums of posterior expectations
#' (allows processing to be performed in chunks).
#'
#' @export
#'
e_step_withColSums <- function(old_pi, Dmat) {
    .Call(`_Primo_e_step_withColSums`, old_pi, Dmat)
}

#' M Step
#'
#' Estimates the \eqn{\pi} vector that maximizes the posterior expectation function from the E-step.
#'
#' @param old_B matrix of posterior expectations/probabilities ; usually
#' from an expectation (E-)step
#'
#' @return Returns a row vector estimating the proportion of SNPs coming from each configuration.
#'
#' @export
#'
m_step <- function(old_B) {
    .Call(`_Primo_m_step`, old_B)
}

#' EM Iteration
#'
#' Complete one iteration of the EM-algorithm (combines E-step and M-step).
#' Calculate posterior expectations given current estimate for \eqn{\pi} (the
#' proportion of SNPs coming from each configuration; E-Step).
#' Re-estimates the \eqn{\pi} vector that maximizes the posterior expectation function from the E-step (i.e. M-step).
#'
#' @param old_pi vector of configuration proportions, fit through maximization
#' (usualy 2^J for J data types)
#' @param Dmat matrix of conditional joint densities under each configuration
#'
#' @return Returns a row vector estimating the proportion of SNPs coming from each configuration.
#'
#' @export
#'
em_iter <- function(old_pi, Dmat) {
    .Call(`_Primo_em_iter`, old_pi, Dmat)
}

