# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' E Step
#'
#' Calculate posterior expectations given maximized estimate for \eqn{\pi} (the
#' proportion of SNPs coming from each configuration).
#'
#' @param old_pi vector of configuration proportions, fit through maximization
#' (usualy 2^J for J data types)
#' @param Q matrix of configurations
#' @param D0 estimate for the null density function
#' @param D1 estimate for the alternative density function
#'
#' @return Returns a vector estimating the posterior expectations
#' (i.e. estimated probability of each configuration for each SNP).
#'
#' @export
#'
e_step <- function(old_pi, Q, D0, D1) {
    .Call(`_primo_e_step`, old_pi, Q, D0, D1)
}

#' M Step
#'
#' Estimates the \eqn{\pi} vector that maximizes the posterior expectation function from the E-step.
#'
#' @param old_B matrix of posterior expectations/probabilities ; usually
#' from an expectation (E-)step
#'
#' @return Returns a vector estimating the proportion of SNPs coming from each configuration.
#'
#' @export
#'
m_step <- function(old_B) {
    .Call(`_primo_m_step`, old_B)
}

#' EM Iteration
#'
#' Complete one iteration of the EM-algorithm (combines E-step and M-step).
#' Calculate posterior expectations given current estimate for \eqn{\pi} (the
#' proportion of SNPs coming from each configuration; E-Step).
#' Re-estimates the \eqn{\pi} vector that maximizes the posterior expectation function from the E-step (i.e. M-step).
#'
#' @param old_pi vector of configuration proportions, fit through maximization
#' (usualy 2^J for J data types)
#' @param Q matrix of configurations
#' @param D0 estimate for the null density function
#' @param D1 estimate for the alternative density function
#'
#' @return Returns a vector estimating the proportion of SNPs coming from each configuration.
#'
#' @export
#'
em_iter <- function(old_pi, Q, D0, D1) {
    .Call(`_primo_em_iter`, old_pi, Q, D0, D1)
}

